---
title: "BoxplottedList"
author: "PaulEndymion"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BoxplottedList}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### build and get the result
```{r}
library(GetToIt)

magic <- list(list(c(rnorm(20,2,1)), c(rnorm(8,8,1))),
              list(c(rnorm(20,3,1)), c(rnorm(8,7,1))),                   
              list(c(rnorm(20,4,1)), c(rnorm(8,6,1)))) 

#give a name to the boxplot
names(magic) <- c(1:length(magic))

#and pick an order
order= c(1,3,2)

p <- ggBoxPlot(magic, order)
```

### The list ...
```{r, echo=FALSE, results = "asis"}

head(magic, n = 2)

```

### ... back as a dataframe ... :

```{r, echo=FALSE, results = "asis"}
pander::pandoc.table(head(as.data.frame(p[2]), n = 30))
```



### ... to be boxplotted.

```{r,fig.width=8, fig.height=5 , tidy.opts=list(blank=FALSE, width.cutoff=55)}
p[1]
```
